import {
  AlertCircle,
  Award,
  Badge,
  Bell,
  Bitcoin,
  Bolt,
  Book,
  Briefcase,
  Building,
  CalendarCheck,
  Captions,
  CheckCircle,
  Code,
  Codepen,
  Coffee,
  File as DocumentIcon,
  Euro,
  Eye,
  File,
  FileQuestion,
  FileText,
  Flag,
  Ghost,
  Gift,
  Grid,
  Heart,
  HelpCircle,
  Kanban,
  Key,
  Layout,
  LayoutGrid,
  LifeBuoy,
  MessageSquare,
  Monitor,
  Network,
  Users as PeopleIcon,
  Plug,
  ScrollText,
  Settings,
  Share2,
  Shield,
  ShieldUser,
  ShoppingCart,
  SquareMousePointer,
  Star,
  Theater,
  TrendingUp,
  UserCheck,
  UserCircle,
  Users,
  Briefcase as WorkIcon,
  Zap,
  Menu,
  PanelsTopLeft,
} from 'lucide-react';

export const MENU_ADMIN_SIDEBAR = [
  {
    title: 'Dashboards',
    icon: LayoutGrid,
    path: '/admin',
  },
  {
    title: 'เมนู',
    icon: Menu,
    children: [
      { title: 'เมนูหลัก', path: '/admin/main-menu' },
    ]
  },
  {
    title: 'เนื้อหา',
    icon: PanelsTopLeft,
    children: [
      { title: 'เนื้อหาหน้าแรก', path: '/admin/homepage' },
      { title: 'เนื้อหาคอนเทนต์', path: '/admin/content' },
    ]
  },
  // {
  //   title: 'Public Profile',
  //   icon: UserCircle,
  //   children: [
  //     {
  //       title: 'Profiles',
  //       children: [
  //         { title: 'Default', path: '/public-profile/profiles/default' },
  //         { title: 'Creator', path: '/public-profile/profiles/creator' },
  //         { title: 'Company', path: '/public-profile/profiles/company' },
  //         { title: 'NFT', path: '/public-profile/profiles/nft' },
  //         { title: 'Blogger', path: '/public-profile/profiles/blogger' },
  //         { title: 'CRM', path: '/public-profile/profiles/crm' },
  //         {
  //           title: 'More',
  //           collapse: true,
  //           collapseTitle: 'Show less',
  //           expandTitle: 'Show 4 more',
  //           children: [
  //             { title: 'Gamer', path: '/public-profile/profiles/gamer' },
  //             { title: 'Feeds', path: '/public-profile/profiles/feeds' },
  //             { title: 'Plain', path: '/public-profile/profiles/plain' },
  //             { title: 'Modal', path: '/public-profile/profiles/modal' },
  //           ],
  //         },
  //       ],
  //     },
  //     {
  //       title: 'Projects',
  //       children: [
  //         { title: '3 Columns', path: '/public-profile/projects/3-columns' },
  //         { title: '2 Columns', path: '/public-profile/projects/2-columns' },
  //       ],
  //     },
  //     { title: 'Works', path: '/public-profile/works' },
  //     { title: 'Teams', path: '/public-profile/teams' },
  //     { title: 'Network', path: '/public-profile/network' },
  //     { title: 'Activity', path: '/public-profile/activity' },
  //   ],
  // },
];